name: Build Android App Bundle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.6

      - name: Grant Execute Permission for Gradle Wrapper
        run: chmod +x gradlew

      # Compiles a clean, standard release bundle file
      - name: Build Release AAB
        run: ./gradlew :app:bundleRelease --no-daemon

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: neon-rush-release-aab
          path: app/build/outputs/bundle/release/app-release.aab
  
